name: redux_persist_flutter_example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: "flutter"
  redux_persist_flutter: ^0.9.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2

# Used for development
#dependency_overrides:
#  redux_persist:
#    path: ../redux_persist
#  redux_persist_flutter:
#    path: ..
