name: redux_persist_web_example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux_persist_web:
    path: ..
  redux: ^5.0.0

# Used for development
#dependency_overrides:
#  redux_persist:
#    path: ../redux_persist
